export type FieldLabel = { ar: string; en: string }

export const FIELD_LABELS: Record<string, FieldLabel> = {
  expires_at: { ar: 'تاريخ الانتهاء', en: 'Expiration date' },
  starts_at: { ar: 'وقت البداية', en: 'Start time' },
  ends_at: { ar: 'وقت النهاية', en: 'End time' },
  end_date: { ar: 'تاريخ النهاية', en: 'End date' },
  start_date: { ar: 'تاريخ البداية', en: 'Start date' },
  due_at: { ar: 'تاريخ الاستحقاق', en: 'Due date' },
  issued_at: { ar: 'تاريخ الإصدار', en: 'Issue date' },
  issue_date: { ar: 'تاريخ إصدار العرض', en: 'Quote issue date' },
  expiry_date: { ar: 'تاريخ الانتهاء', en: 'Expiry date' },
  items: { ar: 'بنود العرض', en: 'Quote line items' },
  hire_date: { ar: 'تاريخ التوظيف', en: 'Hire date' },
  termination_date: { ar: 'تاريخ إنهاء الخدمة', en: 'Termination date' },
  birth_date: { ar: 'تاريخ الميلاد', en: 'Birth date' },
  date: { ar: 'التاريخ', en: 'Date' },
  time: { ar: 'الوقت', en: 'Time' },
  datetime: { ar: 'التاريخ والوقت', en: 'Date and time' },
  email: { ar: 'البريد الإلكتروني', en: 'Email' },
  phone: { ar: 'رقم الهاتف', en: 'Phone number' },
  mobile: { ar: 'رقم الجوال', en: 'Mobile number' },
  name: { ar: 'الاسم', en: 'Name' },
  name_ar: { ar: 'الاسم (عربي)', en: 'Arabic name' },
  address: { ar: 'العنوان', en: 'Address' },
  city: { ar: 'المدينة', en: 'City' },
  timezone: { ar: 'المنطقة الزمنية', en: 'Timezone' },
  tax_number: { ar: 'الرقم الضريبي', en: 'Tax number' },
  cr_number: { ar: 'السجل التجاري', en: 'Commercial registration' },
  iban: { ar: 'الآيبان', en: 'IBAN' },
  bank_name: { ar: 'اسم البنك', en: 'Bank name' },
  amount: { ar: 'المبلغ', en: 'Amount' },
  paid_amount: { ar: 'المبلغ المدفوع', en: 'Paid amount' },
  due_amount: { ar: 'المبلغ المستحق', en: 'Due amount' },
  subtotal: { ar: 'الإجمالي الفرعي', en: 'Subtotal' },
  discount_amount: { ar: 'الخصم', en: 'Discount amount' },
  tax_amount: { ar: 'الضريبة', en: 'Tax amount' },
  total: { ar: 'الإجمالي', en: 'Total' },
  quantity: { ar: 'الكمية', en: 'Quantity' },
  unit_price: { ar: 'سعر الوحدة', en: 'Unit price' },
  cost_price: { ar: 'سعر التكلفة', en: 'Cost price' },
  reorder_point: { ar: 'نقطة إعادة الطلب', en: 'Reorder point' },
  reserved_quantity: { ar: 'الكمية المحجوزة', en: 'Reserved quantity' },
  tax_rate: { ar: 'نسبة الضريبة', en: 'Tax rate' },
  default_vat_rate: { ar: 'نسبة ضريبة القيمة المضافة الافتراضية', en: 'Default VAT rate' },
  invoice_number: { ar: 'رقم الفاتورة', en: 'Invoice number' },
  reference_number: { ar: 'الرقم المرجعي', en: 'Reference number' },
  invoice_id: { ar: 'الفاتورة', en: 'Invoice' },
  product_id: { ar: 'الصنف', en: 'Product' },
  service_id: { ar: 'الخدمة', en: 'Service' },
  employee_id: { ar: 'الموظف', en: 'Employee' },
  assigned_to: { ar: 'المسند إليه', en: 'Assignee' },
  role: { ar: 'الدور', en: 'Role' },
  permissions: { ar: 'الصلاحيات', en: 'Permissions' },
  password: { ar: 'كلمة المرور', en: 'Password' },
  password_confirmation: { ar: 'تأكيد كلمة المرور', en: 'Password confirmation' },
  supplier_id: { ar: 'المورد', en: 'Supplier' },
  branch_id: { ar: 'الفرع', en: 'Branch' },
  customer_id: { ar: 'العميل', en: 'Customer' },
  company_id: { ar: 'الشركة', en: 'Company' },
  vehicle_id: { ar: 'المركبة', en: 'Vehicle' },
  bay_id: { ar: 'الرافعة', en: 'Bay' },
  duration_minutes: { ar: 'المدة بالدقائق', en: 'Duration (minutes)' },
  capability: { ar: 'نوع الخدمة', en: 'Capability' },
  source: { ar: 'المصدر', en: 'Source' },
  status: { ar: 'الحالة', en: 'Status' },
}

