<?php

return [
    'roles' => [
        'owner' => ['*'],

        'manager' => [
            'intelligence.governance.record',
            'branches.view',
            'branches.create',
            'branches.update',
            'users.view',
            'users.create',
            'users.update',
            'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
            'vehicles.view',
            'vehicles.create',
            'vehicles.update',
            'vehicles.delete',
            'products.view',
            'products.create',
            'products.update',
            'inventory.view',
            'inventory.adjust',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'work_orders.view',
            'work_orders.create',
            'work_orders.update',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'purchases.view',
            'purchases.create',
            'reports.view',
            'cross_branch_access',
        ],

        'cashier' => [
            'customers.view',
            'customers.create',
            'customers.update',
            'vehicles.view',
            'products.view',
            'inventory.view',
            'invoices.view',
            'invoices.create',
            'work_orders.view',
        ],

        'accountant' => [
            'customers.view',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'reports.view',
            'purchases.view',
            'suppliers.view',
        ],

        'technician' => [
            'vehicles.view',
            'work_orders.view',
            'work_orders.update',
            'inventory.view',
            'products.view',
        ],

        'viewer' => [
            'customers.view',
            'vehicles.view',
            'products.view',
            'inventory.view',
            'invoices.view',
            'work_orders.view',
            'reports.view',
        ],

        // ── طرف العميل (Fleet Side) ──────────────────────────────────────
        // fleet_contact: موظف مخول من الجهة العميلة — يُنشئ الطلبات ويشحن الرصيد
        'fleet_contact' => [
            'fleet.wallet.topup',
            'fleet.wallet.view',
            'fleet.workorder.create',
            'fleet.workorder.view',
            'fleet.vehicles.view',
        ],

        // fleet_manager: مدير مالي/مخول من الجهة العميلة — يعتمد طلبات الائتمان
        'fleet_manager' => [
            'fleet.wallet.topup',
            'fleet.wallet.view',
            'fleet.workorder.create',
            'fleet.workorder.view',
            'fleet.workorder.approve',
            'fleet.vehicles.view',
            'fleet.reports.view',
        ],
    ],

    'all_permissions' => [
        'companies.view',
        'companies.update',
        'branches.view',
        'branches.create',
        'branches.update',
        'branches.delete',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'customers.view',
        'customers.create',
        'customers.update',
        'customers.delete',
        'vehicles.view',
        'vehicles.create',
        'vehicles.update',
        'vehicles.delete',
        'products.view',
        'products.create',
        'products.update',
        'products.delete',
        'inventory.view',
        'inventory.adjust',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'invoices.delete',
        'work_orders.view',
        'work_orders.create',
        'work_orders.update',
        'work_orders.delete',
        'suppliers.view',
        'suppliers.create',
        'suppliers.update',
        'suppliers.delete',
        'purchases.view',
        'purchases.create',
        'reports.view',
        'api_keys.manage',
        'webhooks.manage',
        'cross_branch_access',
        'subscriptions.view',
        'subscriptions.manage',
        'fleet.wallet.topup',
        'fleet.wallet.view',
        'fleet.workorder.create',
        'fleet.workorder.view',
        'fleet.workorder.approve',
        'fleet.vehicles.view',
        'fleet.reports.view',
        'fleet.plate.verify',
    ],
];
