<?php

return [
    'roles' => [
        'owner' => ['*'],

        'manager' => [
            'intelligence.governance.record',
            'branches.view',
            'branches.create',
            'branches.update',
            'users.view',
            'users.create',
            'users.update',
            'config_profiles.view',
            'config_profiles.manage',
            'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
            'vehicles.view',
            'vehicles.create',
            'vehicles.update',
            'vehicles.delete',
            'products.view',
            'products.create',
            'products.update',
            'inventory.view',
            'inventory.adjust',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'work_orders.view',
            'work_orders.create',
            'work_orders.update',
            'pricing_policies.view',
            'pricing_policies.manage',
            'customer_groups.view',
            'customer_groups.manage',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'org_units.view',
            'org_units.create',
            'org_units.update',
            'org_units.delete',
            'purchases.view',
            'purchases.create',
            'purchases.platform_settlement.view',
            'purchases.claims.view',
            'purchases.claims.create',
            'purchases.claims.review',
            'reports.view',
            'reports.operations.view',
            'reports.employees.view',
            'reports.financial.view',
            'reports.accounting.view',
            'reports.intelligence.view',
            'cross_branch_access',
            'wallet.top_up_requests.create',
            'wallet.top_up_requests.view',
            'wallet.top_up_requests.review',
            'meetings.create',
            'meetings.update',
            'meetings.close',
            'meetings.view_minutes',
            'meetings.manage_actions',
            // بنود الكتالوج التعاقدي (عقود الحوكمة) — مفصّلة للفصل لاحقًا بين الأدوار
            'contracts.service_items.view',
            'contracts.service_items.create',
            'contracts.service_items.update',
            'contracts.service_items.delete',
            'contracts.service_items.match_preview',
        ],

        /** موظف تشغيل: أوامر عمل + فواتير/نقطة البيع + تقارير تشغيلية/مبيعات أساسية */
        'staff' => [
            'customers.view',
            'customers.create',
            'customers.update',
            'vehicles.view',
            'vehicles.create',
            'vehicles.update',
            'products.view',
            'inventory.view',
            'invoices.view',
            'invoices.create',
            'work_orders.view',
            'work_orders.create',
            'work_orders.update',
            'reports.view',
            'reports.financial.view',
            'reports.operations.view',
            'wallet.top_up_requests.create',
            'wallet.top_up_requests.view',
            'purchases.platform_settlement.view',
            'purchases.claims.view',
            'purchases.claims.create',
        ],

        'cashier' => [
            'customers.view',
            'customers.create',
            'customers.update',
            'vehicles.view',
            'products.view',
            'inventory.view',
            'invoices.view',
            'invoices.create',
            'work_orders.view',
            'wallet.top_up_requests.create',
            'wallet.top_up_requests.view',
        ],

        'accountant' => [
            'customers.view',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'reports.view',
            'reports.financial.view',
            'reports.accounting.view',
            'purchases.view',
            'purchases.platform_settlement.view',
            'purchases.claims.view',
            'purchases.claims.review',
            'suppliers.view',
            'wallet.top_up_requests.review',
            'wallet.top_up_requests.view',
        ],

        'technician' => [
            'vehicles.view',
            'work_orders.view',
            'work_orders.update',
            'inventory.view',
            'products.view',
            'purchases.platform_settlement.view',
            'purchases.claims.view',
            'purchases.claims.create',
        ],

        'viewer' => [
            'customers.view',
            'vehicles.view',
            'products.view',
            'inventory.view',
            'invoices.view',
            'work_orders.view',
            'reports.view',
            'reports.operations.view',
        ],

        // ── طرف العميل (Fleet Side) ──────────────────────────────────────
        // fleet_contact: موظف مخول من الجهة العميلة — يُنشئ الطلبات ويشحن الرصيد
        'fleet_contact' => [
            'fleet.wallet.topup',
            'fleet.wallet.view',
            'fleet.workorder.create',
            'fleet.workorder.view',
            'fleet.vehicles.view',
        ],

        // fleet_manager: مدير مالي/مخول من الجهة العميلة — يعتمد طلبات الائتمان
        'fleet_manager' => [
            'fleet.wallet.topup',
            'fleet.wallet.view',
            'fleet.workorder.create',
            'fleet.workorder.view',
            'fleet.workorder.approve',
            'fleet.vehicles.view',
            'fleet.reports.view',
            'reports.operations.view',
        ],

        /** تسجيل عبر الجوال — إكمال الملف فقط (بدون مستأجر) */
        'phone_onboarding' => [
            'phone_registration.flow',
        ],
    ],

    'all_permissions' => [
        'phone_registration.flow',
        'companies.view',
        'companies.update',
        'branches.view',
        'branches.create',
        'branches.update',
        'branches.delete',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'config_profiles.view',
        'config_profiles.manage',
        'customers.view',
        'customers.create',
        'customers.update',
        'customers.delete',
        'vehicles.view',
        'vehicles.create',
        'vehicles.update',
        'vehicles.delete',
        'products.view',
        'products.create',
        'products.update',
        'products.delete',
        'inventory.view',
        'inventory.adjust',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'invoices.delete',
        'work_orders.view',
        'work_orders.create',
        'work_orders.update',
        'work_orders.delete',
        'pricing_policies.view',
        'pricing_policies.manage',
        'customer_groups.view',
        'customer_groups.manage',
        'suppliers.view',
        'suppliers.create',
        'suppliers.update',
        'suppliers.delete',
        'org_units.view',
        'org_units.create',
        'org_units.update',
        'org_units.delete',
        'purchases.view',
        'purchases.create',
        'purchases.platform_settlement.view',
        'purchases.claims.view',
        'purchases.claims.create',
        'purchases.claims.review',
        'reports.view',
        'reports.operations.view',
        'reports.employees.view',
        'reports.financial.view',
        'reports.accounting.view',
        'reports.intelligence.view',
        'api_keys.manage',
        'webhooks.manage',
        'cross_branch_access',
        'subscriptions.view',
        'subscriptions.manage',
        'fleet.wallet.topup',
        'fleet.wallet.view',
        'fleet.workorder.create',
        'fleet.workorder.view',
        'fleet.workorder.approve',
        'fleet.vehicles.view',
        'fleet.reports.view',
        'fleet.plate.verify',
        'meetings.create',
        'meetings.update',
        'meetings.close',
        'meetings.view_minutes',
        'meetings.manage_actions',
        'wallet.top_up_requests.create',
        'wallet.top_up_requests.view',
        'wallet.top_up_requests.review',
        // عقد — بنود كتالوج تعاقدي (مسار governance/contracts/.../service-items)
        'contracts.service_items.view',
        'contracts.service_items.create',
        'contracts.service_items.update',
        'contracts.service_items.delete',
        'contracts.service_items.match_preview',
    ],
];
