<?php

declare(strict_types=1);

/**
 * platform_role (users.platform_role) → permission keys.
 * Use '*' for full platform authority.
 */
return [
    'roles' => [
        'super_admin' => ['*'],
        'platform_admin' => [
            'platform.ops.read',
            'platform.audit.read',
            'platform.companies.read',
            'platform.companies.operational',
            'platform.tenant_nav.manage',
            'platform.subscription.manage',
            'platform.vertical.assign',
            'platform.financial_model.manage',
            'platform.cancellations.read',
            'platform.cancellations.manage',
            'platform.announcement.read',
            'platform.announcement.manage',
            'platform.registration.read',
            'platform.registration.manage',
            'platform.reporting.read',
            'platform.reporting.export',
            'platform.catalog.manage',
            'platform.support.read',
            'platform.support.manage',
            'platform.notifications.read',
            'platform.intelligence.signals.read',
            'platform.intelligence.candidates.read',
            'platform.intelligence.incidents.read',
            'platform.intelligence.incidents.materialize',
            'platform.intelligence.decisions.read',
            'platform.intelligence.incidents.acknowledge',
            'platform.intelligence.incidents.assign_owner',
            'platform.intelligence.incidents.escalate',
            'platform.intelligence.incidents.resolve',
            'platform.intelligence.incidents.close',
            'platform.intelligence.decisions.write',
            'platform.intelligence.guided_workflows.execute',
            'platform.intelligence.controlled_actions.view',
            'platform.intelligence.controlled_actions.create_follow_up',
            'platform.intelligence.controlled_actions.request_human_review',
            'platform.intelligence.controlled_actions.link_task_reference',
            'platform.intelligence.controlled_actions.assign_owner',
            'platform.intelligence.controlled_actions.schedule',
            'platform.intelligence.controlled_actions.complete',
            'platform.intelligence.controlled_actions.cancel',
            'platform.intelligence.controlled_actions.reopen',
            'platform.pricing.view',
            'platform.pricing.create',
            'platform.pricing.review',
            'platform.pricing.approve',
            'platform.providers.manage',
        ],
        /** تسعير المنصة — إنشاء طلبات فقط */
        'platform_pricing_creator' => [
            'platform.pricing.view',
            'platform.pricing.create',
        ],
        /** مراجعة وتوصية ثم إرسال للاعتماد */
        'platform_pricing_reviewer' => [
            'platform.pricing.view',
            'platform.pricing.review',
        ],
        /** اعتماد / رفض / إعادة للتعديل */
        'platform_pricing_approver' => [
            'platform.pricing.view',
            'platform.pricing.approve',
        ],
        /** مزودو الخدمة وتكاليفهم (لا تُعرض للعميل من واجهات المستأجر) */
        'platform_providers_admin' => [
            'platform.pricing.view',
            'platform.providers.manage',
        ],
        'support_agent' => [
            'platform.companies.read',
            'platform.support.read',
            'platform.support.manage',
            'platform.notifications.read',
            'platform.registration.read',
            'platform.registration.manage',
            'platform.announcement.read',
            'platform.intelligence.signals.read',
            'platform.intelligence.candidates.read',
            'platform.intelligence.incidents.read',
            'platform.intelligence.incidents.materialize',
            'platform.intelligence.decisions.read',
            'platform.intelligence.incidents.acknowledge',
            'platform.intelligence.incidents.assign_owner',
            'platform.intelligence.decisions.write',
            'platform.intelligence.guided_workflows.execute',
            'platform.intelligence.controlled_actions.view',
            'platform.intelligence.controlled_actions.create_follow_up',
            'platform.intelligence.controlled_actions.request_human_review',
            'platform.intelligence.controlled_actions.link_task_reference',
            'platform.intelligence.controlled_actions.assign_owner',
            'platform.intelligence.controlled_actions.schedule',
            'platform.intelligence.controlled_actions.complete',
            'platform.intelligence.controlled_actions.cancel',
            'platform.intelligence.controlled_actions.reopen',
        ],
        'finance_admin' => [
            'platform.companies.read',
            'platform.support.read',
            'platform.notifications.read',
            'platform.financial_model.manage',
            'platform.subscription.manage',
            'platform.reporting.read',
            'platform.reporting.export',
            'platform.intelligence.signals.read',
            'platform.intelligence.candidates.read',
            'platform.intelligence.incidents.read',
            'platform.intelligence.decisions.read',
        ],
        'operations_admin' => [
            'platform.ops.read',
            'platform.companies.read',
            'platform.companies.operational',
            'platform.vertical.assign',
            'platform.cancellations.read',
            'platform.cancellations.manage',
            'platform.support.read',
            'platform.support.manage',
            'platform.notifications.read',
            'platform.reporting.read',
            'platform.intelligence.signals.read',
            'platform.intelligence.candidates.read',
            'platform.intelligence.incidents.read',
            'platform.intelligence.incidents.materialize',
            'platform.intelligence.decisions.read',
            'platform.intelligence.incidents.acknowledge',
            'platform.intelligence.incidents.assign_owner',
            'platform.intelligence.incidents.escalate',
            'platform.intelligence.incidents.resolve',
            'platform.intelligence.incidents.close',
            'platform.intelligence.decisions.write',
            'platform.intelligence.guided_workflows.execute',
            'platform.intelligence.controlled_actions.view',
            'platform.intelligence.controlled_actions.create_follow_up',
            'platform.intelligence.controlled_actions.request_human_review',
            'platform.intelligence.controlled_actions.link_task_reference',
            'platform.intelligence.controlled_actions.assign_owner',
            'platform.intelligence.controlled_actions.schedule',
            'platform.intelligence.controlled_actions.complete',
            'platform.intelligence.controlled_actions.cancel',
            'platform.intelligence.controlled_actions.reopen',
        ],
        'auditor' => [
            'platform.audit.read',
            'platform.companies.read',
            'platform.support.read',
            'platform.reporting.read',
            'platform.notifications.read',
            'platform.intelligence.signals.read',
            'platform.intelligence.candidates.read',
            'platform.intelligence.incidents.read',
            'platform.intelligence.decisions.read',
            'platform.intelligence.controlled_actions.view',
        ],
    ],
];
