<?php

/**
 * كتالوج آمن لعرض «قدرات النظام» — قراءة فقط، بدون أسرار تشغيل أو مسارات إدارية داخلية.
 * يُقيَّم لكل مستخدم حسب: الدور، الصلاحيات، ومصفوفة نشاط المنشأة (عدة أنشطة).
 *
 * @see \App\Services\SystemCapabilitiesService
 */
return [
    'items' => [
        [
            'id' => 'dashboard', 'sort' => 10,
            'section' => ['ar' => 'التشغيل', 'en' => 'Operations'],
            'title' => ['ar' => 'لوحة التحكم', 'en' => 'Dashboard'],
            'description' => ['ar' => 'ملخصات وقراءة للوضع التشغيلي.', 'en' => 'Operational summary and KPIs.'],
            'path' => '/', 'feature_gate' => 'operations', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'pos', 'sort' => 20,
            'section' => ['ar' => 'التشغيل', 'en' => 'Operations'],
            'title' => ['ar' => 'نقطة البيع', 'en' => 'Point of sale'],
            'description' => ['ar' => 'بيع وخدمات في الوقت الفعلي.', 'en' => 'Real-time sales and services.'],
            'path' => '/pos', 'feature_gate' => 'operations', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'work_orders', 'sort' => 30,
            'section' => ['ar' => 'التشغيل', 'en' => 'Operations'],
            'title' => ['ar' => 'أوامر العمل', 'en' => 'Work orders'],
            'description' => ['ar' => 'دورة تنفيذ واعتماد حسب الصلاحيات.', 'en' => 'Execution lifecycle with role-based access.'],
            'path' => '/work-orders', 'feature_gate' => 'operations', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'bookings', 'sort' => 40,
            'section' => ['ar' => 'التشغيل', 'en' => 'Operations'],
            'title' => ['ar' => 'الحجوزات', 'en' => 'Bookings'],
            'description' => ['ar' => 'جدولة المواعيد مع العملاء.', 'en' => 'Customer appointment scheduling.'],
            'path' => '/bookings', 'feature_gate' => 'operations', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'meetings', 'sort' => 50,
            'section' => ['ar' => 'التشغيل', 'en' => 'Operations'],
            'title' => ['ar' => 'الاجتماعات', 'en' => 'Meetings'],
            'description' => ['ar' => 'تنسيق اجتماعات ومحاضر وفق الصلاحية.', 'en' => 'Meetings and minutes where permitted.'],
            'path' => '/meetings', 'feature_gate' => 'operations', 'permission' => 'meetings.update', 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'invoices', 'sort' => 110,
            'section' => ['ar' => 'المالية', 'en' => 'Finance'],
            'title' => ['ar' => 'الفواتير', 'en' => 'Invoices'],
            'description' => ['ar' => 'إصدار ومتابعة الفواتير والمدفوعات.', 'en' => 'Invoicing and payment tracking.'],
            'path' => '/invoices', 'feature_gate' => 'finance', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'financial_reconciliation', 'sort' => 115,
            'section' => ['ar' => 'المالية', 'en' => 'Finance'],
            'title' => ['ar' => 'المطابقة المالية', 'en' => 'Financial reconciliation'],
            'description' => ['ar' => 'مراجعة مطابقة وفق صلاحية التقارير المالية.', 'en' => 'Reconciliation views for authorized finance roles.'],
            'path' => '/financial-reconciliation', 'feature_gate' => 'finance', 'permission' => 'reports.financial.view', 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'wallet', 'sort' => 120,
            'section' => ['ar' => 'المالية', 'en' => 'Finance'],
            'title' => ['ar' => 'المحفظة', 'en' => 'Wallet'],
            'description' => ['ar' => 'أرصدة تشغيلية وحركات مرتبطة بالمنشأة.', 'en' => 'Operational balances and movements.'],
            'path' => '/wallet', 'feature_gate' => 'finance', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'purchases', 'sort' => 130,
            'section' => ['ar' => 'المالية', 'en' => 'Finance'],
            'title' => ['ar' => 'المشتريات', 'en' => 'Purchases'],
            'description' => ['ar' => 'أوامر شراء واستلام بضائع.', 'en' => 'Purchase orders and goods receipt.'],
            'path' => '/purchases', 'feature_gate' => 'finance', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'supplier_contract_layer',
            'sort' => 135,
            'section' => ['ar' => 'طبقة العقود (Contract Layer)', 'en' => 'Contract layer'],
            'title' => ['ar' => 'عقود الموردين (PDF والتنبيهات)', 'en' => 'Supplier contracts (PDF & alerts)'],
            'description' => [
                'ar' => 'حوكمة عقود التوريد مع تواريخ انتهاء وتنبيهات — يعتمد على نشاط المنشأة.',
                'en' => 'Supplier contract governance with expiry and alerts — gated by business profile.',
            ],
            'path' => '/suppliers',
            'feature_gate' => 'supplier_contract_mgmt',
            'permission' => 'suppliers.view',
            'requires_manager' => false,
            'rollout' => 'live',
        ],
        [
            'id' => 'customer_contracts',
            'sort' => 138,
            'section' => ['ar' => 'طبقة العقود (Contract Layer)', 'en' => 'Contract layer'],
            'title' => ['ar' => 'عقود واتفاقيات (واجهة العملاء التشغيلية)', 'en' => 'Operational contracts workspace'],
            'description' => ['ar' => 'مسار عقود تشغيلية داخل المنشأة — يقتصر عادة على الإدارة.', 'en' => 'In-tenant contract workspace — typically manager-level.'],
            'path' => '/contracts', 'feature_gate' => 'finance', 'permission' => null, 'requires_manager' => true, 'rollout' => 'live',
        ],
        [
            'id' => 'ledger',
            'sort' => 210,
            'section' => ['ar' => 'المحاسبة', 'en' => 'Accounting'],
            'title' => ['ar' => 'دفتر القيود', 'en' => 'General ledger entries'],
            'description' => ['ar' => 'قيود يومية وفق إعداد المحاسبة.', 'en' => 'Journal entries per company setup.'],
            'path' => '/ledger', 'feature_gate' => 'accounting', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'chart_of_accounts',
            'sort' => 220,
            'section' => ['ar' => 'المحاسبة', 'en' => 'Accounting'],
            'title' => ['ar' => 'شجرة الحسابات', 'en' => 'Chart of accounts'],
            'description' => ['ar' => 'هيكل الحسابات المحاسبية.', 'en' => 'Account hierarchy.'],
            'path' => '/chart-of-accounts', 'feature_gate' => 'accounting', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'zatca',
            'sort' => 230,
            'section' => ['ar' => 'المحاسبة والامتثال', 'en' => 'Accounting & compliance'],
            'title' => ['ar' => 'الضريبة والامتثال (ZATCA)', 'en' => 'Tax & ZATCA compliance'],
            'description' => ['ar' => 'إعدادات ومسارات امتثال — تخضع للتدقيق المحلي.', 'en' => 'Compliance-oriented settings; subject to local audit.'],
            'path' => '/zatca', 'feature_gate' => 'accounting', 'permission' => null, 'requires_manager' => true, 'rollout' => 'live',
        ],
        [
            'id' => 'fixed_assets',
            'sort' => 235,
            'section' => ['ar' => 'المحاسبة', 'en' => 'Accounting'],
            'title' => ['ar' => 'الأصول الثابتة', 'en' => 'Fixed assets'],
            'description' => [
                'ar' => 'سجل أصول وإهلاك — يُفعّل من ملف نشاط المنشأة؛ التنفيذ الفني مرحلي.',
                'en' => 'Asset register and depreciation — gated in the business profile; technical rollout is phased.',
            ],
            'path' => '/fixed-assets',
            'feature_gate' => 'fixed_assets',
            'permission' => 'reports.accounting.view',
            'requires_manager' => false,
            'rollout' => 'planned',
        ],
        [
            'id' => 'inventory',
            'sort' => 310,
            'section' => ['ar' => 'المخزون', 'en' => 'Inventory'],
            'title' => ['ar' => 'المنتجات والمخزون', 'en' => 'Products & inventory'],
            'description' => ['ar' => 'أصناف، وحدات، حركات ومخزون.', 'en' => 'SKUs, units, stock movements.'],
            'path' => '/products', 'feature_gate' => 'inventory', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'org_structure',
            'sort' => 320,
            'section' => ['ar' => 'الهيكل التنظيمي', 'en' => 'Org structure'],
            'title' => ['ar' => 'الهيكل الهرمي (قطاعات وأقسام)', 'en' => 'Hierarchical org units'],
            'description' => ['ar' => 'شجرة تنظيمية — قد تُعطّل افتراضياً لبعض الأنشطة (مثل التجزئة).', 'en' => 'Org tree — may be off by default for some verticals (e.g. retail).'],
            'path' => '/settings/org-units', 'feature_gate' => 'org_structure', 'permission' => null, 'requires_manager' => true, 'rollout' => 'live',
        ],
        [
            'id' => 'fleet_wallet',
            'sort' => 410,
            'section' => ['ar' => 'الأسطول', 'en' => 'Fleet'],
            'title' => ['ar' => 'محافظ الأسطول والتحقق من اللوحة', 'en' => 'Fleet wallets & plate checks'],
            'description' => ['ar' => 'ميزات أسطول تظهر عند تفعيل نشاط الأسطول في المنشأة.', 'en' => 'Fleet features when enabled for the tenant profile.'],
            'path' => '/fleet/wallet', 'feature_gate' => 'fleet', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'reports',
            'sort' => 510,
            'section' => ['ar' => 'التقارير', 'en' => 'Reporting'],
            'title' => ['ar' => 'التقارير', 'en' => 'Reports'],
            'description' => ['ar' => 'تقارير تشغيلية ومالية حسب الدور.', 'en' => 'Operational and financial reports by role.'],
            'path' => '/reports', 'feature_gate' => 'reports', 'permission' => null, 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'business_intelligence',
            'sort' => 520,
            'section' => ['ar' => 'التحليلات', 'en' => 'Analytics'],
            'title' => ['ar' => 'ذكاء الأعمال (لوحة BI)', 'en' => 'Business intelligence'],
            'description' => ['ar' => 'تحليلات متقدمة عند تفعيل باقة الذكاء.', 'en' => 'Advanced analytics when intelligence is enabled.'],
            'path' => '/business-intelligence', 'feature_gate' => 'intelligence', 'permission' => null, 'requires_manager' => false, 'rollout' => 'beta',
        ],
        [
            'id' => 'command_center',
            'sort' => 530,
            'section' => ['ar' => 'التحليلات', 'en' => 'Analytics'],
            'title' => ['ar' => 'مركز العمليات الذكي', 'en' => 'Intelligence command center'],
            'description' => ['ar' => 'لوحة داخلية قد تُعطّل في بناء الواجهة — الصلاحية على الخادم تبقى الحَكَم.', 'en' => 'Internal board; may be disabled in frontend build — server permissions remain authoritative.'],
            'path' => '/internal/intelligence', 'feature_gate' => 'intelligence', 'permission' => 'reports.intelligence.view', 'requires_manager' => false, 'rollout' => 'beta',
        ],
        [
            'id' => 'governance_console',
            'sort' => 540,
            'section' => ['ar' => 'الحوكمة', 'en' => 'Governance'],
            'title' => ['ar' => 'حوكمة السياسات', 'en' => 'Policy governance'],
            'description' => ['ar' => 'إعداد قواعد تنعكس على التنفيذ — يتطلب صلاحية إدارة مستخدمين.', 'en' => 'Policy rules affecting execution — requires elevated user-admin permission.'],
            'path' => '/governance', 'feature_gate' => 'reports', 'permission' => 'users.update', 'requires_manager' => false, 'rollout' => 'live',
        ],
        [
            'id' => 'supplier_portal',
            'sort' => 610,
            'section' => ['ar' => 'بوابات خارجية', 'en' => 'External portals'],
            'title' => ['ar' => 'بوابة المورد (موقوفة)', 'en' => 'Supplier portal (not planned)'],
            'description' => [
                'ar' => 'قرار منتج: لا تُبنى بوابة ويب مستقلة للمورد؛ يبقى التعامل عبر قنوات المنشأة الحالية (مثل الموردون والمشتريات داخل النظام).',
                'en' => 'Product scope: no dedicated supplier web portal; workflows stay inside the tenant app (e.g. suppliers & purchases).',
            ],
            'path' => null, 'feature_gate' => null, 'permission' => null, 'requires_manager' => false, 'rollout' => 'cancelled',
        ],
        [
            'id' => 'driver_field_app',
            'sort' => 620,
            'section' => ['ar' => 'الميدان', 'en' => 'Field'],
            'title' => ['ar' => 'تطبيق ميداني (بعد النشر)', 'en' => 'Native field app (post-launch)'],
            'description' => [
                'ar' => 'تطبيق أصلي للميدان ليس ضمن إصدار الإطلاق الأول؛ يُراجع بعد استقرار النشر والويب.',
                'en' => 'A native field app is out of scope for the initial launch; to be revisited after the web rollout stabilizes.',
            ],
            'path' => null, 'feature_gate' => null, 'permission' => null, 'requires_manager' => false, 'rollout' => 'post_launch',
        ],
    ],
];
