<?php

namespace Database\Seeders;

use App\Models\Plugin;
use Illuminate\Database\Seeder;

/**
 * كتالوج إضافات السوق — مرتبة حسب recommended_rank (الأصغر = يظهر أولاً كـ «موصى به»).
 * السعر المعروض في الواجهة: أداء/اشتراك المزود + 20٪ رسوم منصة (تحسب في الواجهة).
 */
class PluginsCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $catalog = [
            [
                'plugin_key' => 'int_qiwa_workforce',
                'name' => 'Qiwa Workforce & Contracts',
                'name_ar' => 'تكامل قوى — العمالة والعقود',
                'description_ar' => 'مزامنة بيانات العمالة، العقود، وإشعارات وزارة الموارد البشرية. يقلل الإدخال اليدوي ويربط ملف الموظف بمرجع قوى بعد اعتماد الربط الرسمي.',
                'category' => 'integration',
                'icon' => 'building-office-2',
                'module_scope' => ['workshop', 'employees', 'hr'],
                'hooks' => ['onEmployeeCreated', 'onContractSigned'],
                'is_premium' => true,
                'price_monthly' => 199,
                'rating' => 4.9,
                'recommended_rank' => 1,
                'tags' => ['recommended', 'hr', 'qiwa', 'labor', 'saudi'],
            ],
            [
                'plugin_key' => 'int_gosi_payroll',
                'name' => 'GOSI Payroll Sync',
                'name_ar' => 'تكامل التأمينات الاجتماعية (GOSI)',
                'description_ar' => 'ربط أجور الموظفين واشتراكات GOSI، وتنبيهات عند اختلاف المبلغ المُبلَّغ عن الراتب في النظام. للمراجعة والامتثال بعد تفعيل بوابة المؤسسة.',
                'category' => 'integration',
                'icon' => 'shield-check',
                'module_scope' => ['workshop', 'employees', 'payroll'],
                'hooks' => ['onPayrollClosed', 'onEmployeeSalaryChanged'],
                'is_premium' => true,
                'price_monthly' => 149,
                'rating' => 4.85,
                'recommended_rank' => 2,
                'tags' => ['recommended', 'hr', 'gosi', 'insurance', 'saudi'],
            ],
            [
                'plugin_key' => 'int_e_contract',
                'name' => 'E-Contracting (Nafath / Docu-sign style)',
                'name_ar' => 'التعاقد الإلكتروني والتوقيع',
                'description_ar' => 'إدارة مسار العقد الإلكتروني: مسودة، بانتظار التوقيع، مؤرشف — مع تذكيرات وربط بملف الموظف. يتكامل مع مزودي التوقيع المعتمدين بعد التكوين.',
                'category' => 'integration',
                'icon' => 'document-text',
                'module_scope' => ['workshop', 'employees', 'governance'],
                'hooks' => ['onContractRequested', 'onContractSigned'],
                'is_premium' => true,
                'price_monthly' => 89,
                'rating' => 4.8,
                'recommended_rank' => 3,
                'tags' => ['recommended', 'hr', 'contract', 'nafath', 'compliance'],
            ],
            [
                'plugin_key' => 'notify_smart_hub',
                'name' => 'Smart Notifications Hub',
                'name_ar' => 'مركز التنبيهات الذكية',
                'description_ar' => 'قنوات متعددة: بريد، SMS، واتساب (حسب التكامل)، مع قواعد «متى تُرسل» واختناق لتفادي الإزعاج. مناسب للمدراء وفرق الورش.',
                'category' => 'ui',
                'icon' => 'bell-alert',
                'module_scope' => ['notifications', 'dashboard', 'work_orders'],
                'hooks' => ['onAlertRaised', 'onWorkOrderDelayed'],
                'is_premium' => true,
                'price_monthly' => 39,
                'rating' => 4.75,
                'recommended_rank' => 4,
                'tags' => ['recommended', 'alerts', 'sms', 'whatsapp'],
            ],
            [
                'plugin_key' => 'int_mudad_payroll',
                'name' => 'Mudad Wage File',
                'name_ar' => 'ملف أجور مدد',
                'description_ar' => 'توليد ملفات أجور متوافقة مع منصة مدد، مع فحص استحقاق الخصومات والبدلات قبل الإرسال.',
                'category' => 'integration',
                'icon' => 'banknotes',
                'module_scope' => ['workshop', 'payroll'],
                'hooks' => ['onPayrollExport'],
                'is_premium' => true,
                'price_monthly' => 59,
                'rating' => 4.7,
                'recommended_rank' => 5,
                'tags' => ['hr', 'mudad', 'payroll', 'saudi'],
            ],
            [
                'plugin_key' => 'int_zatca_enhanced',
                'name' => 'ZATCA Enhanced Compliance',
                'name_ar' => 'زاتكا — امتثال وتشخيص',
                'description_ar' => 'فحص فواتير XML، حالة الربط، وتنبيهات قبل انتهاء الشهادة أو رفض الإرسال.',
                'category' => 'integration',
                'icon' => 'document-check',
                'module_scope' => ['invoices', 'zatca'],
                'hooks' => ['onInvoiceIssued', 'onZatcaRejected'],
                'is_premium' => false,
                'price_monthly' => 0,
                'rating' => 4.9,
                'recommended_rank' => 6,
                'tags' => ['recommended', 'zatca', 'compliance', 'free-tier'],
            ],
            [
                'plugin_key' => 'ai_advanced_diagnostics',
                'name' => 'AI Advanced Diagnostics',
                'name_ar' => 'التشخيص الذكي المتقدم للمركبات',
                'description_ar' => 'تحليل أعطال محتملة من الأعراض، مع درجة ثقة وتكلفة تقديرية — لورش السيارات.',
                'category' => 'ai',
                'icon' => 'cpu-chip',
                'module_scope' => ['vehicles', 'work_orders'],
                'hooks' => ['onVehicleView', 'onWorkOrderCreated'],
                'is_premium' => false,
                'price_monthly' => 0,
                'rating' => 4.8,
                'recommended_rank' => 10,
                'tags' => ['ai', 'workshop', 'vehicles'],
            ],
            [
                'plugin_key' => 'ai_pricing_engine',
                'name' => 'Dynamic Pricing AI',
                'name_ar' => 'محرك التسعير الذكي',
                'description_ar' => 'توصيات أسعار الخدمات والقطع حسب الطلب والموسم وبيانات داخلية.',
                'category' => 'ai',
                'icon' => 'currency-dollar',
                'module_scope' => ['services', 'invoices'],
                'hooks' => ['onInvoiceGenerated'],
                'is_premium' => true,
                'price_monthly' => 49,
                'rating' => 4.65,
                'recommended_rank' => 14,
                'tags' => ['ai', 'pricing'],
            ],
            [
                'plugin_key' => 'ai_fraud_detection',
                'name' => 'Fraud Detection AI',
                'name_ar' => 'كشف الاحتيال الذكي',
                'description_ar' => 'تحليل أنماط المدفوعات والفواتير للإشارة لمعاملات حساسة.',
                'category' => 'ai',
                'icon' => 'shield-exclamation',
                'module_scope' => ['invoices', 'wallet'],
                'hooks' => ['onPaymentProcessed'],
                'is_premium' => true,
                'price_monthly' => 99,
                'rating' => 4.9,
                'recommended_rank' => 18,
                'tags' => ['ai', 'risk', 'wallet'],
            ],
            [
                'plugin_key' => 'ai_customer_support',
                'name' => 'AI Support Bot',
                'name_ar' => 'بوت الدعم الذكي',
                'description_ar' => 'إجابات مبدئية وتوجيه التذاكر حسب نية العميل.',
                'category' => 'ai',
                'icon' => 'chat-bubble-left-right',
                'module_scope' => ['support'],
                'hooks' => ['onSupportTicketCreated'],
                'is_premium' => false,
                'price_monthly' => 0,
                'rating' => 4.5,
                'recommended_rank' => 22,
                'tags' => ['ai', 'support'],
            ],
            [
                'plugin_key' => 'ai_inventory_optimizer',
                'name' => 'Inventory Optimizer',
                'name_ar' => 'تحسين المخزون الذكي',
                'description_ar' => 'تنبؤات إعادة الطلب وتنبيهات نقص القطع.',
                'category' => 'ai',
                'icon' => 'cube',
                'module_scope' => ['inventory', 'products'],
                'hooks' => ['onInventoryLow'],
                'is_premium' => false,
                'price_monthly' => 0,
                'rating' => 4.7,
                'recommended_rank' => 24,
                'tags' => ['ai', 'inventory'],
            ],
            [
                'plugin_key' => 'whatsapp_ai_bot',
                'name' => 'WhatsApp Business AI',
                'name_ar' => 'بوت واتساب الذكي',
                'description_ar' => 'تأكيد الحجوزات، إشعارات أوامر العمل، ومتابعة العملاء عبر واتساب.',
                'category' => 'integration',
                'icon' => 'chat-bubble-oval-left',
                'module_scope' => ['notifications', 'customers', 'bookings'],
                'hooks' => ['onWorkOrderStatusChange'],
                'is_premium' => true,
                'price_monthly' => 29,
                'rating' => 4.6,
                'recommended_rank' => 12,
                'tags' => ['integration', 'whatsapp'],
            ],
            [
                'plugin_key' => 'revenue_intelligence',
                'name' => 'Revenue Intelligence',
                'name_ar' => 'ذكاء الإيرادات والتنبؤ',
                'description_ar' => 'لوحات عميقة، تجزئة الفروع، ونِسَب التحصيل.',
                'category' => 'analytics',
                'icon' => 'chart-bar',
                'module_scope' => ['reports'],
                'hooks' => ['onDashboardLoad'],
                'is_premium' => true,
                'price_monthly' => 79,
                'rating' => 4.88,
                'recommended_rank' => 16,
                'tags' => ['analytics', 'reports'],
            ],
            [
                'plugin_key' => 'analytics_bays_heatmap',
                'name' => 'Bay Utilization Heatmap',
                'name_ar' => 'خريطة حرارة مناطق العمل',
                'description_ar' => 'التقاط الاختناقات وتوزيع الأحمال على السُّلال والورديات.',
                'category' => 'analytics',
                'icon' => 'squares-2x2',
                'module_scope' => ['bays', 'work_orders'],
                'hooks' => ['onBayReleased'],
                'is_premium' => true,
                'price_monthly' => 45,
                'rating' => 4.55,
                'recommended_rank' => 26,
                'tags' => ['analytics', 'bays'],
            ],
            [
                'plugin_key' => 'customer_emotion_ai',
                'name' => 'Customer Sentiment AI',
                'name_ar' => 'تحليل مشاعر العملاء',
                'description_ar' => 'من التقييمات والمحادثات — لتحسين NPS.',
                'category' => 'ai',
                'icon' => 'face-smile',
                'module_scope' => ['support', 'customers'],
                'hooks' => ['onNpsReceived'],
                'is_premium' => true,
                'price_monthly' => 59,
                'rating' => 4.4,
                'recommended_rank' => 28,
                'tags' => ['ai', 'crm'],
            ],
            [
                'plugin_key' => 'int_sms_gateway',
                'name' => 'SMS Gateway (Unifonic / CEQUENS style)',
                'name_ar' => 'بوابة الرسائل القصيرة',
                'description_ar' => 'OTP، تذكير بالمواعيد، وإشعارات الدفع عبر مزودي SMS المعتمدين.',
                'category' => 'integration',
                'icon' => 'device-phone-mobile',
                'module_scope' => ['notifications'],
                'hooks' => ['onOtpRequested'],
                'is_premium' => true,
                'price_monthly' => 19,
                'rating' => 4.5,
                'recommended_rank' => 30,
                'tags' => ['sms', 'notifications'],
            ],
            [
                'plugin_key' => 'fleet_maps_pro',
                'name' => 'Fleet & Vehicle Maps',
                'name_ar' => 'خرائط الأسطول والمركبات',
                'description_ar' => 'آخر موقع، مسار الصيانة، وتجميع مركبات العملاء.',
                'category' => 'integration',
                'icon' => 'map',
                'module_scope' => ['vehicles', 'fleet'],
                'hooks' => ['onVehicleLocationUpdate'],
                'is_premium' => true,
                'price_monthly' => 35,
                'rating' => 4.45,
                'recommended_rank' => 32,
                'tags' => ['fleet', 'maps'],
            ],
            [
                'plugin_key' => 'ui_branded_portal',
                'name' => 'Branded Customer Portal',
                'name_ar' => 'بوابة عميل بعلامتكم',
                'description_ar' => 'ألوان، شعار، ونطاق فرعي — لتجربة موحدة.',
                'category' => 'ui',
                'icon' => 'paint-brush',
                'module_scope' => ['portal', 'bookings'],
                'hooks' => ['onPortalLoad'],
                'is_premium' => true,
                'price_monthly' => 25,
                'rating' => 4.35,
                'recommended_rank' => 34,
                'tags' => ['ui', 'branding'],
            ],
        ];

        foreach ($catalog as $p) {
            Plugin::updateOrCreate(
                ['plugin_key' => $p['plugin_key']],
                array_merge($p, [
                    'description' => $p['description'] ?? ($p['description_ar'] ?? ''),
                    'version' => $p['version'] ?? '1.0.0',
                    'author' => $p['author'] ?? 'أسس برو / شركاء المنصة',
                    'supported_plans' => $p['supported_plans'] ?? ['professional', 'enterprise'],
                    'is_active' => true,
                    'install_count' => $p['install_count'] ?? random_int(200, 9000),
                    'config_schema' => $p['config_schema'] ?? ['auto_alerts' => true, 'min_confidence' => 75],
                ])
            );
        }

        $this->command?->info('PluginsCatalogSeeder: '.count($catalog).' إضافة.');
    }
}
